- name: Generate RSS file
  run: |
    # Fetch namedays for Slovakia
    api_response=$(curl -s "https://nameday.abalin.net/api/V2/today/Bratislava")

    # Validate API response
    if echo "$api_response" | jq empty 2>/dev/null; then
      namedays_sk=$(echo "$api_response" | jq -r '.data.sk')
      
      if [ "$namedays_sk" == "null" ] || [ -z "$namedays_sk" ]; then
        echo "Error: Namedays data is missing from the API response." >&2
        exit 1
      fi
    else
      echo "Error: Invalid API response. Cannot parse JSON." >&2
      exit 1
    fi

    # Generate RSS file
    echo '<?xml version="1.0" encoding="UTF-8" ?>' > meniny.xml
    echo '<rss version="2.0">' >> meniny.xml
    echo '    <channel>' >> meniny.xml
    echo '        <title>Meniny na Slovensku</title>' >> meniny.xml
    echo '        <link>https://github.com/DKR450/workflows/blob/main/meniny.xml</link>' >> meniny.xml
    echo '        <description>Meniny na Slovensku pre dnešný deň</description>' >> meniny.xml
    echo '        <language>sk</language>' >> meniny.xml
    echo '        <item>' >> meniny.xml
    echo '            <title>Dnes má meniny '$namedays_sk'</title>' >> meniny.xml
    echo '            <link>https://github.com/DKR450/workflows/blob/main/meniny.xml</link>' >> meniny.xml
    echo '            <description>Dnes má meniny '$namedays_sk'</description>' >> meniny.xml
    echo '            <pubDate>'$(date -R)'</pubDate>' >> meniny.xml
    echo '        </item>' >> meniny.xml
    echo '    </channel>' >> meniny.xml
    echo '</rss>' >> meniny.xml
